#Tugas membuat biodata sederhana menggunakan python
#Nama: Naufal Ilham Fauzan
#NIM: 2502106

nama = input("Masukkan nama: ")
nim = int(input("Masukkan NIM: "))
umur = int(input("Masukkan umur: "))
jenis_kelamin = input("Masukkan jenis kelamin: ")
alamat = input("Masukkan alamat: ")
tinggi_badan = float(input("Masukkan tinggi badan (cm): "))
berat_badan = float(input("Masukkan berat badan (kg): "))
apakah_mahasiswa = bool(int(input("Apakah Anda seorang mahasiswa? (1/0): ")))
apakah_bekerja = bool(int(input("Apakah Anda bekerja? (1/0): ")))
apakah_menikah = bool(int(input("Apakah Anda menikah? (1/0): ")))
apakah_berpacaran = bool(int(input("Apakah Anda berpacaran? (1/0): ")))
hewan_peliharaan = input("Nama hewan peliharaan: ")
makanan_favorit = input("Masukkan makanan favorit: ")
minuman_favorit = input("Masukkan minuman favorit: ")
hobi = input("Masukkan hobi: ")
game_favorit = input("Masukkan game favorit: ")
film_favorit = input("Masukkan film favorit: ")
matakuliah_favorit = input("Masukkan mata kuliah favorit: ")
dosen_favorit = input("Masukkan nama dosen favorit: ")
kampus_favorit = input("Masukkan nama kampus favorit: ")

print(" ")
print("=========================================")
print("             BIODATA SEDERHANA           ")
print("=========================================")
print("Nama             :", nama)
print("NIM              :", nim)
print("Umur             :", umur)
print("Jenis Kelamin    :", jenis_kelamin)
print("Alamat           :", alamat)
print("Tinggi Badan     :", tinggi_badan, "cm")
print("Berat Badan      :", berat_badan, "kg")
print("=========================================")
print("Status Mahasiswa :", apakah_mahasiswa)
print("Status Bekerja   :", apakah_bekerja)
print("Status Menikah   :", apakah_menikah)
print("Status Berpacaran:", apakah_berpacaran)
print("=========================================")
print("Hewan Peliharaan :", hewan_peliharaan)
print("Makanan Favorit  :", makanan_favorit)
print("Minuman Favorit  :", minuman_favorit)
print("Hobi             :", hobi)
print("Game Favorit     :", game_favorit)
print("Film Favorit     :", film_favorit)
print("Mata Kuliah Fav  :", matakuliah_favorit)
print("Dosen Favorit    :", dosen_favorit)
print("Kampus Favorit   :", kampus_favorit)
print("=========================================")
print(" ")